[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[[functions]]
  path = "/check-alerts"
  schedule = "*/2 * * * *"
